
CREATE TABLE "T_CATEGORY" (
  "ID" VARCHAR2(64) NOT NULL,
  "CODE" VARCHAR2(20) NOT NULL,
  "NAME" VARCHAR2(20) NOT NULL,
  PRIMARY KEY ("ID")
)
NOCOMPRESS
NOPARALLEL ;

COMMENT ON TABLE "T_CATEGORY" IS '分类表';
COMMENT ON COLUMN "T_CATEGORY"."ID" IS '主键';
COMMENT ON COLUMN "T_CATEGORY"."CODE" IS '代码';
COMMENT ON COLUMN "T_CATEGORY"."NAME" IS '类型名';

ALTER TABLE "T_MATERIEL" ADD FOREIGN KEY ("MATERIEL_CATEGORY_ID") REFERENCES "T_CATEGORY" ("ID");



/*
  create by longshuzhen
  2016/10/27
  员工表
 */
CREATE TABLE "KCGL"."T_EMPLOYEE" (
  "ID" NUMBER(20) NOT NULL ,
  "CODE" VARCHAR2(20 BYTE) NOT NULL ,
  "NAME" VARCHAR2(50 BYTE) NULL ,
  "POSITION" VARCHAR2(100 BYTE) NULL ,
  "COMPANY_CODE" VARCHAR2(20 BYTE) NOT NULL ,
  "SUPPER_CODE" VARCHAR2(20 BYTE) NULL ,
  "DEPARTMENT_CODE" VARCHAR2(20 BYTE) NOT NULL ,
  "POSITION_LEVEL" VARCHAR2(20 BYTE) NULL ,
  "MAIL" VARCHAR2(50 BYTE) NULL ,
  "MOBILE" VARCHAR2(20 BYTE) NULL ,
  "TEL" VARCHAR2(30 BYTE) NULL ,
  "QQ" VARCHAR2(20 BYTE) NULL ,
  "SEX" VARCHAR2(5 BYTE) NULL ,
  "IDENTIFICATION" VARCHAR2(20 BYTE) NULL ,
  "REG_DATE" DATE NULL ,
  "CREATE_BY" VARCHAR2(20 BYTE) NULL ,
  "UPDATE_BY" VARCHAR2(20 BYTE) NULL ,
  "CREATE_TIME" TIMESTAMP(6)  NULL ,
  "UPDATE_TIME" TIMESTAMP(6)  NULL ,
  "STATUS" VARCHAR2(10 BYTE) NULL ,
  "TS01" VARCHAR2(22 BYTE) NULL ,
  "TURN_POSITIVE_DATE" DATE NULL ,
  "EMPLOYEE_STATUS" VARCHAR2(10 BYTE) NULL ,
  "CERTIFICATE_TYPE" VARCHAR2(50 BYTE) NULL ,
  "REPORT_TO" VARCHAR2(20 BYTE) NULL ,
  "EMPLOYMENT_TYPE" VARCHAR2(10 BYTE) NULL ,
  "PROBATION_MONTH" VARCHAR2(2 BYTE) NULL ,
  "ATTENDANCE_AWARD" NUMBER DEFAULT 100  NULL ,
  "POSITION_TYPE" VARCHAR2(2 BYTE) NULL ,
  "JOB_CONNECTOR" VARCHAR2(20 BYTE) NULL
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "KCGL"."T_EMPLOYEE"."CODE" IS '员工ID';
COMMENT ON COLUMN "KCGL"."T_EMPLOYEE"."NAME" IS '员工名称';
COMMENT ON COLUMN "KCGL"."T_EMPLOYEE"."POSITION" IS '员工职位';
COMMENT ON COLUMN "KCGL"."T_EMPLOYEE"."COMPANY_CODE" IS '所属公司';
COMMENT ON COLUMN "KCGL"."T_EMPLOYEE"."SUPPER_CODE" IS '上级名称';
COMMENT ON COLUMN "KCGL"."T_EMPLOYEE"."DEPARTMENT_CODE" IS '所属部门';
COMMENT ON COLUMN "KCGL"."T_EMPLOYEE"."POSITION_LEVEL" IS '职位等级';
COMMENT ON COLUMN "KCGL"."T_EMPLOYEE"."MAIL" IS '邮箱';
COMMENT ON COLUMN "KCGL"."T_EMPLOYEE"."MOBILE" IS '手机号';
COMMENT ON COLUMN "KCGL"."T_EMPLOYEE"."TEL" IS '座机';
COMMENT ON COLUMN "KCGL"."T_EMPLOYEE"."QQ" IS 'QQ号';
COMMENT ON COLUMN "KCGL"."T_EMPLOYEE"."SEX" IS '性别';
COMMENT ON COLUMN "KCGL"."T_EMPLOYEE"."IDENTIFICATION" IS '身份证号';
COMMENT ON COLUMN "KCGL"."T_EMPLOYEE"."REG_DATE" IS '入职时间';
COMMENT ON COLUMN "KCGL"."T_EMPLOYEE"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "KCGL"."T_EMPLOYEE"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "KCGL"."T_EMPLOYEE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "KCGL"."T_EMPLOYEE"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "KCGL"."T_EMPLOYEE"."STATUS" IS '状态：0-删除；1-启用；';
COMMENT ON COLUMN "KCGL"."T_EMPLOYEE"."TS01" IS '数据库同步时间戳';
COMMENT ON COLUMN "KCGL"."T_EMPLOYEE"."TURN_POSITIVE_DATE" IS '转正日期';
COMMENT ON COLUMN "KCGL"."T_EMPLOYEE"."EMPLOYEE_STATUS" IS '员工在职情况：0-试用；1-正式；2-离职；';
COMMENT ON COLUMN "KCGL"."T_EMPLOYEE"."CERTIFICATE_TYPE" IS '证件类型';
COMMENT ON COLUMN "KCGL"."T_EMPLOYEE"."REPORT_TO" IS '汇报对象';
COMMENT ON COLUMN "KCGL"."T_EMPLOYEE"."EMPLOYMENT_TYPE" IS '用工性质';
COMMENT ON COLUMN "KCGL"."T_EMPLOYEE"."PROBATION_MONTH" IS '试用期时长';
COMMENT ON COLUMN "KCGL"."T_EMPLOYEE"."ATTENDANCE_AWARD" IS '考勤奖';
COMMENT ON COLUMN "KCGL"."T_EMPLOYEE"."POSITION_TYPE" IS '岗位性质 1-营运岗 0-非营运岗 2-业务岗 3-技术岗'';';
COMMENT ON COLUMN "KCGL"."T_EMPLOYEE"."JOB_CONNECTOR" IS '工作交接人，取值本表CODE列值'';';

-- ----------------------------
-- Indexes structure for table T_EMPLOYEE
-- ----------------------------

-- ----------------------------
-- Checks structure for table T_EMPLOYEE
-- ----------------------------
ALTER TABLE "KCGL"."T_EMPLOYEE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "KCGL"."T_EMPLOYEE" ADD CHECK ("CODE" IS NOT NULL);
ALTER TABLE "KCGL"."T_EMPLOYEE" ADD CHECK ("COMPANY_CODE" IS NOT NULL);
ALTER TABLE "KCGL"."T_EMPLOYEE" ADD CHECK ("DEPARTMENT_CODE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table T_EMPLOYEE
-- ----------------------------
ALTER TABLE "KCGL"."T_EMPLOYEE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Foreign Key structure for table "KCGL"."T_EMPLOYEE"
-- ----------------------------
ALTER TABLE "KCGL"."T_EMPLOYEE" ADD FOREIGN KEY ("DEPARTMENT_CODE") REFERENCES "KCGL"."T_DEPARTMENT" ("CODE");
ALTER TABLE "KCGL"."T_EMPLOYEE" ADD FOREIGN KEY ("COMPANY_CODE") REFERENCES "KCGL"."T_COMPANY" ("CODE");


/*
部门表
 */
CREATE TABLE "KCGL"."T_DEPARTMENT" (
  "ID" NUMBER(20) NOT NULL ,
  "CODE" VARCHAR2(20 BYTE) NOT NULL ,
  "NAME" VARCHAR2(50 BYTE) NULL ,
  "DESCRIPTION" VARCHAR2(200 BYTE) NULL ,
  "SUPER_CODE" VARCHAR2(16 BYTE) NULL ,
  "COMPANY_CODE" VARCHAR2(20 BYTE) NULL ,
  "EMPLOYEE_CODE" VARCHAR2(20 BYTE) NULL ,
  "CREATE_BY" VARCHAR2(20 BYTE) NULL ,
  "UPDATE_BY" VARCHAR2(20 BYTE) NULL ,
  "CREATE_TIME" TIMESTAMP(6)  NULL ,
  "UPDATE_TIME" TIMESTAMP(6)  NULL ,
  "STATUS" VARCHAR2(10 BYTE) NULL ,
  "MEMO" VARCHAR2(200 BYTE) NULL ,
  "TS01" VARCHAR2(22 BYTE) NULL ,
  "CENTER_CODE" VARCHAR2(20 BYTE) NULL ,
  "EFFECTIVE_DATE" DATE NULL
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "KCGL"."T_DEPARTMENT" IS '部门';
COMMENT ON COLUMN "KCGL"."T_DEPARTMENT"."CODE" IS '部门代码';
COMMENT ON COLUMN "KCGL"."T_DEPARTMENT"."NAME" IS '部门名称';
COMMENT ON COLUMN "KCGL"."T_DEPARTMENT"."DESCRIPTION" IS '部门简介';
COMMENT ON COLUMN "KCGL"."T_DEPARTMENT"."SUPER_CODE" IS '上级部门代码';
COMMENT ON COLUMN "KCGL"."T_DEPARTMENT"."COMPANY_CODE" IS '所属公司';
COMMENT ON COLUMN "KCGL"."T_DEPARTMENT"."EMPLOYEE_CODE" IS '负责人';
COMMENT ON COLUMN "KCGL"."T_DEPARTMENT"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "KCGL"."T_DEPARTMENT"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "KCGL"."T_DEPARTMENT"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "KCGL"."T_DEPARTMENT"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "KCGL"."T_DEPARTMENT"."STATUS" IS '状态';
COMMENT ON COLUMN "KCGL"."T_DEPARTMENT"."MEMO" IS '备注';
COMMENT ON COLUMN "KCGL"."T_DEPARTMENT"."TS01" IS '时间戳';
COMMENT ON COLUMN "KCGL"."T_DEPARTMENT"."CENTER_CODE" IS '所属中心';
COMMENT ON COLUMN "KCGL"."T_DEPARTMENT"."EFFECTIVE_DATE" IS '生效时间';

-- ----------------------------
-- Indexes structure for table T_DEPARTMENT
-- ----------------------------

-- ----------------------------
-- Uniques structure for table T_DEPARTMENT
-- ----------------------------
ALTER TABLE "KCGL"."T_DEPARTMENT" ADD UNIQUE ("CODE");

-- ----------------------------
-- Checks structure for table T_DEPARTMENT
-- ----------------------------
ALTER TABLE "KCGL"."T_DEPARTMENT" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "KCGL"."T_DEPARTMENT" ADD CHECK ("CODE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table T_DEPARTMENT
-- ----------------------------
ALTER TABLE "KCGL"."T_DEPARTMENT" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Foreign Key structure for table "KCGL"."T_DEPARTMENT"
-- ----------------------------
ALTER TABLE "KCGL"."T_DEPARTMENT" ADD FOREIGN KEY ("COMPANY_CODE") REFERENCES "KCGL"."T_COMPANY" ("CODE");

/*
   公司表
 */
CREATE TABLE "KCGL"."T_COMPANY" (
  "ID" NUMBER(20) NOT NULL ,
  "CODE" VARCHAR2(10 BYTE) NOT NULL ,
  "NAME" VARCHAR2(80 BYTE) NULL ,
  "ADDRESS" VARCHAR2(80 BYTE) NULL ,
  "REP" VARCHAR2(40 BYTE) NULL ,
  "EMPLOYEE_CODE" VARCHAR2(20 BYTE) NULL ,
  "FAX" VARCHAR2(20 BYTE) NULL ,
  "TEL" VARCHAR2(40 BYTE) NULL ,
  "TAX_NO" VARCHAR2(40 BYTE) NULL ,
  "BANK" VARCHAR2(60 BYTE) NULL ,
  "ACCOUNT" VARCHAR2(40 BYTE) NULL ,
  "ZIP" VARCHAR2(6 BYTE) NULL ,
  "SUPER_CODE" VARCHAR2(10 BYTE) NULL ,
  "CREATE_BY" VARCHAR2(20 BYTE) NULL ,
  "UPDATE_BY" VARCHAR2(20 BYTE) NULL ,
  "CREATE_TIME" TIMESTAMP(6)  NULL ,
  "UPDATE_TIME" TIMESTAMP(6)  NULL ,
  "STATUS" VARCHAR2(10 BYTE) NULL ,
  "MEMO" VARCHAR2(200 BYTE) NULL ,
  "TS01" VARCHAR2(22 BYTE) NULL ,
  "EFFECTIVE_DATE" DATE NULL
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "KCGL"."T_COMPANY" IS '公司信息,金力数据表JL_GSXX';
COMMENT ON COLUMN "KCGL"."T_COMPANY"."CODE" IS '公司代码';
COMMENT ON COLUMN "KCGL"."T_COMPANY"."NAME" IS '公司名称';
COMMENT ON COLUMN "KCGL"."T_COMPANY"."ADDRESS" IS '公司地址';
COMMENT ON COLUMN "KCGL"."T_COMPANY"."REP" IS '法人代表';
COMMENT ON COLUMN "KCGL"."T_COMPANY"."EMPLOYEE_CODE" IS '总经理';
COMMENT ON COLUMN "KCGL"."T_COMPANY"."FAX" IS '传真号码';
COMMENT ON COLUMN "KCGL"."T_COMPANY"."TEL" IS '联系电话';
COMMENT ON COLUMN "KCGL"."T_COMPANY"."TAX_NO" IS '税号';
COMMENT ON COLUMN "KCGL"."T_COMPANY"."BANK" IS '开户银行';
COMMENT ON COLUMN "KCGL"."T_COMPANY"."ACCOUNT" IS '帐号';
COMMENT ON COLUMN "KCGL"."T_COMPANY"."ZIP" IS '邮政编码';
COMMENT ON COLUMN "KCGL"."T_COMPANY"."SUPER_CODE" IS '上级代码';
COMMENT ON COLUMN "KCGL"."T_COMPANY"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "KCGL"."T_COMPANY"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "KCGL"."T_COMPANY"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "KCGL"."T_COMPANY"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "KCGL"."T_COMPANY"."STATUS" IS '状态';
COMMENT ON COLUMN "KCGL"."T_COMPANY"."MEMO" IS '备注';
COMMENT ON COLUMN "KCGL"."T_COMPANY"."TS01" IS '时间戳';
COMMENT ON COLUMN "KCGL"."T_COMPANY"."EFFECTIVE_DATE" IS '生效时间';

-- ----------------------------
-- Indexes structure for table T_COMPANY
-- ----------------------------

-- ----------------------------
-- Uniques structure for table T_COMPANY
-- ----------------------------
ALTER TABLE "KCGL"."T_COMPANY" ADD UNIQUE ("CODE");

-- ----------------------------
-- Checks structure for table T_COMPANY
-- ----------------------------
ALTER TABLE "KCGL"."T_COMPANY" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "KCGL"."T_COMPANY" ADD CHECK ("CODE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table T_COMPANY
-- ----------------------------
ALTER TABLE "KCGL"."T_COMPANY" ADD PRIMARY KEY ("ID");